spring:
  datasource:
    url: jdbc:postgresql://db:5432/woodblocktoys
    username: postgres
    password: pepe256
    platform: postgres
    driverClassName: org.postgresql.Driver

  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

server:
  port : 8080